# log-level = "info"

[external-storage]
# url = "s3://tistream/bucket1"
# security-key = ""
# access-key = ""

[dispatcher]
# addr = "127.0.0.1"
# port = 20991

## Prefix of data change buffer
# prefix = ""
## Check store changes interval, in seconds
# check-store-interval = 10
## Check file changes interval, in seconds.
# check-file-interval = 5

[sorter]
# addr = "127.0.0.1"
# port = 20992

[meta-server]
# addr = "127.0.0.1"
# port = 20993
# mysql-host = ""
# mysql-port = ""
# mysql-user = ""
# mysql-password = ""
## Update meta-server lease interval, in seconds.
# update-lease-interval = 5
## Master lease duration, in seconds.
# lease-duration = 10

[api-server]
# addr = "127.0.0.1"
# port = 20994

[schema-registry]
# addr = "127.0.0.1"
# port = 20995