# log-level = "info"

[dispatcher]
# addr = "127.0.0.1"
# port = 20991

## Check store changes interval, in seconds
# check-store-interval = 10
## Check file changes interval, in seconds.
# check-file-interval = 5

## MetaServer Endpoints
# meta-sever-endpoints = ["127.0.0.1:20993", "127.0.0.2:20993"]
## If isolated from the meta-server exceeded suicide-dur, the dispatcher will be paused.
# suicide-dur = 10

[dispatcher.storage]
# region = "us-west-1"
# bucket = ""
# prefix = "data-change-buffer"
# access-key = ""
# secure-key = ""

[sorter]
# addr = "127.0.0.1"
# port = 20992

[meta-server]
# addr = "127.0.0.1"
# port = 20993
# mysql-host = ""
# mysql-port = ""
# mysql-user = ""
# mysql-password = ""
## Update meta-server lease interval, in seconds.
# update-lease-interval = 5
## Master lease duration, in seconds.
# lease-duration = 10

[api-server]
# addr = "127.0.0.1"
# port = 20994

[schema-registry]
# addr = "127.0.0.1"
# port = 20995