// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: metapb.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskOp int32

const (
	TaskOp_Attach TaskOp = 0
	TaskOp_Detach TaskOp = 1
)

// Enum value maps for TaskOp.
var (
	TaskOp_name = map[int32]string{
		0: "Attach",
		1: "Detach",
	}
	TaskOp_value = map[string]int32{
		"Attach": 0,
		"Detach": 1,
	}
)

func (x TaskOp) Enum() *TaskOp {
	p := new(TaskOp)
	*p = x
	return p
}

func (x TaskOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskOp) Descriptor() protoreflect.EnumDescriptor {
	return file_metapb_proto_enumTypes[0].Descriptor()
}

func (TaskOp) Type() protoreflect.EnumType {
	return &file_metapb_proto_enumTypes[0]
}

func (x TaskOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskOp.Descriptor instead.
func (TaskOp) EnumDescriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{0}
}

// Upstream notify downstream there are new data change files for specified tenants.
type HasNewChangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId []uint64 `protobuf:"varint,1,rep,packed,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *HasNewChangeReq) Reset() {
	*x = HasNewChangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasNewChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasNewChangeReq) ProtoMessage() {}

func (x *HasNewChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasNewChangeReq.ProtoReflect.Descriptor instead.
func (*HasNewChangeReq) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{0}
}

func (x *HasNewChangeReq) GetTenantId() []uint64 {
	if x != nil {
		return x.TenantId
	}
	return nil
}

type HasNewChangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HasNewChangeResp) Reset() {
	*x = HasNewChangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasNewChangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasNewChangeResp) ProtoMessage() {}

func (x *HasNewChangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasNewChangeResp.ProtoReflect.Descriptor instead.
func (*HasNewChangeResp) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{1}
}

type DispatcherHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string            `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                                  // dispatcher addr, used to distiguish dispatchers.
	Throughput  uint64            `protobuf:"varint,2,opt,name=throughput,proto3" json:"throughput,omitempty"`                     // throughput since last heartbeat.
	TenantStats []*TenantSubStats `protobuf:"bytes,3,rep,name=tenant_stats,json=tenantStats,proto3" json:"tenant_stats,omitempty"` // tenant id and throughput.
}

func (x *DispatcherHeartbeatReq) Reset() {
	*x = DispatcherHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatcherHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherHeartbeatReq) ProtoMessage() {}

func (x *DispatcherHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherHeartbeatReq.ProtoReflect.Descriptor instead.
func (*DispatcherHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{2}
}

func (x *DispatcherHeartbeatReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DispatcherHeartbeatReq) GetThroughput() uint64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *DispatcherHeartbeatReq) GetTenantStats() []*TenantSubStats {
	if x != nil {
		return x.TenantStats
	}
	return nil
}

type DispatcherHeartbeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DispatcherHeartbeatResp) Reset() {
	*x = DispatcherHeartbeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatcherHeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherHeartbeatResp) ProtoMessage() {}

func (x *DispatcherHeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherHeartbeatResp.ProtoReflect.Descriptor instead.
func (*DispatcherHeartbeatResp) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{3}
}

type SorterHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string            `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                                  // sorter addr, used to distiguish dispatchers.
	Throughput  uint64            `protobuf:"varint,2,opt,name=throughput,proto3" json:"throughput,omitempty"`                     // throughput since last heartbeat.
	TenantStats []*TenantSubStats `protobuf:"bytes,3,rep,name=tenant_stats,json=tenantStats,proto3" json:"tenant_stats,omitempty"` // tenant id and throughput.
}

func (x *SorterHeartbeatReq) Reset() {
	*x = SorterHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SorterHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SorterHeartbeatReq) ProtoMessage() {}

func (x *SorterHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SorterHeartbeatReq.ProtoReflect.Descriptor instead.
func (*SorterHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{4}
}

func (x *SorterHeartbeatReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SorterHeartbeatReq) GetThroughput() uint64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *SorterHeartbeatReq) GetTenantStats() []*TenantSubStats {
	if x != nil {
		return x.TenantStats
	}
	return nil
}

type SorterHeartbeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SorterHeartbeatResp) Reset() {
	*x = SorterHeartbeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SorterHeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SorterHeartbeatResp) ProtoMessage() {}

func (x *SorterHeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SorterHeartbeatResp.ProtoReflect.Descriptor instead.
func (*SorterHeartbeatResp) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{5}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   uint64      `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Range      *Task_Range `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	SorterAddr string      `protobuf:"bytes,3,opt,name=sorter_addr,json=sorterAddr,proto3" json:"sorter_addr,omitempty"`
	SnapAddr   string      `protobuf:"bytes,4,opt,name=snap_addr,json=snapAddr,proto3" json:"snap_addr,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Task) GetRange() *Task_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Task) GetSorterAddr() string {
	if x != nil {
		return x.SorterAddr
	}
	return ""
}

func (x *Task) GetSnapAddr() string {
	if x != nil {
		return x.SnapAddr
	}
	return ""
}

type TenantSubStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   uint64      `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Range      *Task_Range `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	Throughput uint64      `protobuf:"varint,3,opt,name=throughput,proto3" json:"throughput,omitempty"`
}

func (x *TenantSubStats) Reset() {
	*x = TenantSubStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantSubStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSubStats) ProtoMessage() {}

func (x *TenantSubStats) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSubStats.ProtoReflect.Descriptor instead.
func (*TenantSubStats) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{7}
}

func (x *TenantSubStats) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantSubStats) GetRange() *Task_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TenantSubStats) GetThroughput() uint64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

type TenantTasksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId uint64  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tasks    []*Task `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Op       TaskOp  `protobuf:"varint,3,opt,name=op,proto3,enum=tistreampb.TaskOp" json:"op,omitempty"`
}

func (x *TenantTasksReq) Reset() {
	*x = TenantTasksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTasksReq) ProtoMessage() {}

func (x *TenantTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTasksReq.ProtoReflect.Descriptor instead.
func (*TenantTasksReq) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{8}
}

func (x *TenantTasksReq) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TenantTasksReq) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TenantTasksReq) GetOp() TaskOp {
	if x != nil {
		return x.Op
	}
	return TaskOp_Attach
}

type TenantTasksResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TenantTasksResp) Reset() {
	*x = TenantTasksResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTasksResp) ProtoMessage() {}

func (x *TenantTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTasksResp.ProtoReflect.Descriptor instead.
func (*TenantTasksResp) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{9}
}

type Task_Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Task_Range) Reset() {
	*x = Task_Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metapb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Range) ProtoMessage() {}

func (x *Task_Range) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Range.ProtoReflect.Descriptor instead.
func (*Task_Range) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Task_Range) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Task_Range) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

var File_metapb_proto protoreflect.FileDescriptor

var file_metapb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x74, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x22, 0x2e, 0x0a, 0x0f, 0x48, 0x61,
	0x73, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x48, 0x61,
	0x73, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x8b,
	0x01, 0x0a, 0x16, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x75, 0x74, 0x12, 0x3d, 0x0a,
	0x0c, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62,
	0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x19, 0x0a, 0x17,
	0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x53, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x70,
	0x75, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x0b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc0, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x6e, 0x61, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x41, 0x64, 0x64, 0x72, 0x1a, 0x2f, 0x0a, 0x05, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x7b, 0x0a, 0x0e, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x68, 0x72, 0x6f,
	0x75, 0x67, 0x68, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x68,
	0x72, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x75, 0x74, 0x22, 0x79, 0x0a, 0x0e, 0x54, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12,
	0x22, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x69,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x70, 0x52,
	0x02, 0x6f, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2a, 0x20, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x70,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x10, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metapb_proto_rawDescOnce sync.Once
	file_metapb_proto_rawDescData = file_metapb_proto_rawDesc
)

func file_metapb_proto_rawDescGZIP() []byte {
	file_metapb_proto_rawDescOnce.Do(func() {
		file_metapb_proto_rawDescData = protoimpl.X.CompressGZIP(file_metapb_proto_rawDescData)
	})
	return file_metapb_proto_rawDescData
}

var file_metapb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metapb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metapb_proto_goTypes = []interface{}{
	(TaskOp)(0),                     // 0: tistreampb.TaskOp
	(*HasNewChangeReq)(nil),         // 1: tistreampb.HasNewChangeReq
	(*HasNewChangeResp)(nil),        // 2: tistreampb.HasNewChangeResp
	(*DispatcherHeartbeatReq)(nil),  // 3: tistreampb.DispatcherHeartbeatReq
	(*DispatcherHeartbeatResp)(nil), // 4: tistreampb.DispatcherHeartbeatResp
	(*SorterHeartbeatReq)(nil),      // 5: tistreampb.SorterHeartbeatReq
	(*SorterHeartbeatResp)(nil),     // 6: tistreampb.SorterHeartbeatResp
	(*Task)(nil),                    // 7: tistreampb.Task
	(*TenantSubStats)(nil),          // 8: tistreampb.TenantSubStats
	(*TenantTasksReq)(nil),          // 9: tistreampb.TenantTasksReq
	(*TenantTasksResp)(nil),         // 10: tistreampb.TenantTasksResp
	(*Task_Range)(nil),              // 11: tistreampb.Task.Range
}
var file_metapb_proto_depIdxs = []int32{
	8,  // 0: tistreampb.DispatcherHeartbeatReq.tenant_stats:type_name -> tistreampb.TenantSubStats
	8,  // 1: tistreampb.SorterHeartbeatReq.tenant_stats:type_name -> tistreampb.TenantSubStats
	11, // 2: tistreampb.Task.range:type_name -> tistreampb.Task.Range
	11, // 3: tistreampb.TenantSubStats.range:type_name -> tistreampb.Task.Range
	7,  // 4: tistreampb.TenantTasksReq.tasks:type_name -> tistreampb.Task
	0,  // 5: tistreampb.TenantTasksReq.op:type_name -> tistreampb.TaskOp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_metapb_proto_init() }
func file_metapb_proto_init() {
	if File_metapb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metapb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasNewChangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasNewChangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatcherHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatcherHeartbeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SorterHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SorterHeartbeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantSubStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantTasksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantTasksResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metapb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metapb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metapb_proto_goTypes,
		DependencyIndexes: file_metapb_proto_depIdxs,
		EnumInfos:         file_metapb_proto_enumTypes,
		MessageInfos:      file_metapb_proto_msgTypes,
	}.Build()
	File_metapb_proto = out.File
	file_metapb_proto_rawDesc = nil
	file_metapb_proto_goTypes = nil
	file_metapb_proto_depIdxs = nil
}
