// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: schemaservicepb.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchemaServiceClient is the client API for SchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaServiceClient interface {
	RegisterSchemaSnap(ctx context.Context, in *RegisterSchemaSnapReq, opts ...grpc.CallOption) (*RegisterSchemaSnapResp, error)
	RegisterDDLChange(ctx context.Context, in *RegisterDDLReq, opts ...grpc.CallOption) (*RegisterDDLResp, error)
}

type schemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaServiceClient(cc grpc.ClientConnInterface) SchemaServiceClient {
	return &schemaServiceClient{cc}
}

func (c *schemaServiceClient) RegisterSchemaSnap(ctx context.Context, in *RegisterSchemaSnapReq, opts ...grpc.CallOption) (*RegisterSchemaSnapResp, error) {
	out := new(RegisterSchemaSnapResp)
	err := c.cc.Invoke(ctx, "/tistreampb.SchemaService/RegisterSchemaSnap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) RegisterDDLChange(ctx context.Context, in *RegisterDDLReq, opts ...grpc.CallOption) (*RegisterDDLResp, error) {
	out := new(RegisterDDLResp)
	err := c.cc.Invoke(ctx, "/tistreampb.SchemaService/RegisterDDLChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServiceServer is the server API for SchemaService service.
// All implementations must embed UnimplementedSchemaServiceServer
// for forward compatibility
type SchemaServiceServer interface {
	RegisterSchemaSnap(context.Context, *RegisterSchemaSnapReq) (*RegisterSchemaSnapResp, error)
	RegisterDDLChange(context.Context, *RegisterDDLReq) (*RegisterDDLResp, error)
	mustEmbedUnimplementedSchemaServiceServer()
}

// UnimplementedSchemaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSchemaServiceServer struct {
}

func (UnimplementedSchemaServiceServer) RegisterSchemaSnap(context.Context, *RegisterSchemaSnapReq) (*RegisterSchemaSnapResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSchemaSnap not implemented")
}
func (UnimplementedSchemaServiceServer) RegisterDDLChange(context.Context, *RegisterDDLReq) (*RegisterDDLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDDLChange not implemented")
}
func (UnimplementedSchemaServiceServer) mustEmbedUnimplementedSchemaServiceServer() {}

// UnsafeSchemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaServiceServer will
// result in compilation errors.
type UnsafeSchemaServiceServer interface {
	mustEmbedUnimplementedSchemaServiceServer()
}

func RegisterSchemaServiceServer(s grpc.ServiceRegistrar, srv SchemaServiceServer) {
	s.RegisterService(&SchemaService_ServiceDesc, srv)
}

func _SchemaService_RegisterSchemaSnap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSchemaSnapReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).RegisterSchemaSnap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tistreampb.SchemaService/RegisterSchemaSnap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).RegisterSchemaSnap(ctx, req.(*RegisterSchemaSnapReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_RegisterDDLChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDDLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).RegisterDDLChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tistreampb.SchemaService/RegisterDDLChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).RegisterDDLChange(ctx, req.(*RegisterDDLReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SchemaService_ServiceDesc is the grpc.ServiceDesc for SchemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tistreampb.SchemaService",
	HandlerType: (*SchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSchemaSnap",
			Handler:    _SchemaService_RegisterSchemaSnap_Handler,
		},
		{
			MethodName: "RegisterDDLChange",
			Handler:    _SchemaService_RegisterDDLChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schemaservicepb.proto",
}
